### ISSUE TITLE
Can't download reference data.

### ISSUE THREAD

**Issue by xenmind** [kl-lab/dejavu#1]
Hi,

I get this error when I try to clone the repository:

'Cloning into 'C:\Users\xen_m\Documents\GitHub\dejavu'...
remote: Enumerating objects: 68, done.        
remote: Counting objects: 100% (68/68), done.        
remote: Compressing objects: 100% (53/53), done.        
remote: Total 68 (delta 22), reused 53 (delta 14), pack-reused 0        
Receiving objects: 100% (68/68), 38.64 KiB | 217.00 KiB/s, done.
Resolving deltas: 100% (22/22), done.
Downloading reference/ref1.RData (276 KB)
Error downloading object: reference/ref1.RData (e971627): Smudge error: Error downloading reference/ref1.RData (e97162759a4e1a3b699bab9094cf26838ee6aea9b11d580d5190bb1529c734e2): [e97162759a4e1a3b699bab9094cf26838ee6aea9b11d580d5190bb1529c734e2] Object does not exist on the server: [404] Object does not exist on the server'

I'm unable to download the reference data, and so the example doesn't work for me.

I was able to install the R package however.

Any help would be appreciated,

Gavin.

**Comment by feng-li** [comment]
Hi, there was a problem with the ref path. I now have reuploaded the reference data. Please try again.

**Comment by xenmind** [comment]
Thanks working now.
